apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" (lower .Release.Name) }}
  namespace: {{ .Release.Name }}
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Release.Name }}
  hostPath:
    path: {{ printf "%s/%s" (lower .Values.kubevirt.mount) (lower .Chart.Name) }}
