kind: ServiceAccount
apiVersion: v1
metadata:
    name: {{.Release.Name}}
    namespace: {{.Release.Name}}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Name}}
rules:
  - apiGroups: ["*"] 
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["*"]
    verbs: ["get", "create", "apply", "update", "patch", "delete", "watch", "list"]

---
kind: ClusterRoleBinding   
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Name}}
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}
    namespace: {{.Release.Name}}
roleRef:
  kind: ClusterRole
  name: {{.Release.Name}}
  apiGroup: rbac.authorization.k8s.io

